# T-Pot (Standard)
# For docker-compose ...
version: '3.2'

services:

# Suricata service
  suricata:
    build:
      context: ./suricata
      dockerfile: Dockerfile
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    volumes:
      - volume_log:/var/log/suricata

  logshipper:
    build:
      context: ./logshipper
      dockerfile: Dockerfile
    links:
      - elasticsearch
    ports:
      - 5044:5044

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data:rw

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  evebox:
    image: jasonish/evebox
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5636:5636
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

volumes:
  elastic_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/storage/elasticsearch'

  volume_log:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/storage/eve'
