# T-Pot (Standard)
# For docker-compose ...
version: '3.2'

services:
# Suricata service
  suricata:
    build:
      context: ./suricata
      dockerfile: Dockerfile
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - volume_log:/var/log/suricata
    labels:
      - traefik.enable=false

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
      - 9200
      - 9300
    environment:
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data:rw
    labels:
      - traefik.enable=false

  logshipper:
    build:
      context: ./logshipper
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - 5044:5044
    labels:
      - traefik.enable=false

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    ports:
      - 5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:kibana.docker.localhost
      - traefik.port=5601

  evebox:
    image: jasonish/evebox:master
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5636
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:evebox.docker.localhost
      - traefik.port=5636

  grafana:
    image: grafana/grafana:5.4.2
    ports:
      - 3000
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:grafana.docker.localhost
      - traefik.port=3000

  reverse-proxy:
    image: traefik:v1.7.6-alpine  # The official Traefik docker image
    command: --docker  # Enables the web UI and tells Traefik to listen to docker
    ports:
      - 80:80
      - 443:443
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik/traefik.toml:/traefik.toml
      - $PWD/traefik/acme.json:/acme.json
    labels:
      - traefik.docker.network=network_proxy
      - traefik.frontend.rule=Host:traefik.docker.localhost
      - traefik.frontend.auth.basic=admin:$$apr1$$Uwy4HMRc$$mO4kAq2Vh3gDoeYZp6kSc0
      - traefik.port=8080

volumes:
  elastic_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/storage/elasticsearch'

  volume_log:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/storage/eve'
