# T-Pot (Standard)
# For docker-compose ...
version: '3.4'

services:
# Suricata service
  suricata:
    build:
      context: ./suricata
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - LISTEN_IFACE=eth0
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - volume_log:/var/log/suricata
    labels:
      - traefik.enable=false

  elasticsearch:
    image: blacktop/elasticsearch:6.5.4
    ports:
      - 9200:9200
      - 9300
    environment:
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data:rw
    labels:
      - traefik.enable=false

  logstash:
    image: blacktop/logstash:6.5.4
    command: -f /etc/logstash/conf.d/
    volumes:
      - $PWD/logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - $PWD/logstash/elasticsearch-template.json:/etc/logstash/elasticsearch-template.json
      - $PWD/logstash/GeoLite2-City.mmdb:/data/GeoLite2-City.mmdb
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - 5044:5044
    labels:
      - traefik.enable=false

  kibana:
    image: blacktop/kibana:6.5.4
    ports:
      - 5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:kibana.docker.localhost
      - traefik.port=5601

  cronjobber:
    build:
      context: ./crontab-ui
      dockerfile: Dockerfile
    ports:
      - 8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:cronjobber.docker.localhost
      - traefik.port=8000

  reverse-proxy:
    image: traefik:v1.7.6-alpine  # The official Traefik docker image
    command: --docker  # Enables the web UI and tells Traefik to listen to docker
    ports:
      - 80:80
      - 443:443
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik/traefik.toml:/traefik.toml
      - $PWD/traefik/acme.json:/acme.json
    labels:
      - traefik.docker.network=network_proxy
      - traefik.frontend.rule=Host:traefik.docker.localhost
      - traefik.frontend.auth.basic=admin:$$apr1$$Uwy4HMRc$$mO4kAq2Vh3gDoeYZp6kSc0
      - traefik.port=8080

volumes:
  elastic_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/storage/elasticsearch'

  volume_log:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/storage/eve'
