filebeat.prospectors:
  - input_type: log
    enabled: true
    paths:
     - "/var/log/suricata/eve.json"
    fields:
        application: suricata
    fields_under_root: true
    json.message_key: log
    json.keys_under_root: true
    json.overwrite_keys: true

output:
  logstash:
    hosts: 'logstash:5044'
  # elasticsearch:
  #   hosts: '127.0.0.1:9200'

logging:
  to_files: false
  to_syslog: false
