filebeat.config.modules.path: "/filebeat/modules.d/*.yml"
filebeat.modules:
- module: suricata
  eve:
    enabled: true
    var.paths:
      - "/var/log/suricata/eve.json"

#filebeat.prospectors:
#  - input_type: log
#    enabled: true
#    paths:
#      - "/var/log/suricata/eve.json"
#    fields:
#        application: suricata
#    fields_under_root: true
#    json.message_key: log
#    json.keys_under_root: true
#    json.overwrite_keys: true

output:
  # logstash:
  #   hosts: ["localhost:5044"]
  elasticsearch:
    hosts: ["localhost:9200"]

logging:
  to_files: false
  to_syslog: false
